let press = reactive([{name: "football",type:"sport",text: "Football is a word which could mean one of several sports. The best-known type of football is association football. This is called 'soccer' in North America, South Africa, and Australia to avoid confusion with other types of football that are commonly played there. The name football comes from the two words 'foot' and 'ball'. It is named football because the players of the game walk and often run (on their feet) while playing, as opposed to (for example) polo where the players ride horses. Football is played using a ball, also called a 'football', that is usually shaped like a sphere or an ellipsoid. The ball is often kicked with the foot, but depending on the game, it can also be hit using other parts of the body (in association football) and handling the ball is a part of some other sports known as 'football'. Players can use any part of their body except their arms and hands. Goalies can use every part of their body to keep the ball out of the goal. Some elements of football have been seen in many countries, dating back to the second and third century AD in China.[1] The modern games of both rugby football and association football comes from 19th-century England.[2] Kicking a ball, in Europe, was described in Britannia (now western Scottish lowlands), in Germania (now Deutchland) and Gallia (now France and northern-central Italy).[3] An evolution goes back to the Middle Ages in Paris.[4] Association football (founded in Richmond, London at the end of 1800) spread to many other parts of Europe, and was brought to the rest of the world with colonization. Today, it is the most popular sport in the world and many people watch it on television, especially the FIFA World Cup that happens every four years. Every year there is a Football Club Competition called as Champions League.All the qualified big teams take part. At the end, we have one winner who takes the prestigious UEFA trophy. All big players lay for their own teams. Some big players who take part every year are Mbappe, Ronaldo, Messi, Dybala, Neymar and many more. ", id:1},
{name:"bascetball",type:"sport",text:"Basketball is a team sport where one team, usually consisting of five players in each team, play against each other on a rectangular court. The objective is to get the ball through a hoop mounted high on a backboard on the opponent's side of the court, while preventing the opponent from shooting it into your team's hoop. It is a very popular sport worldwide, played with a round and usually orange(orange-brown) ball that bounces. Basketball players mainly use skills such as dribbling, shooting, running, and jumping. Each made basket is worth two points, while a basket made from beyond the three-point line is worth three points. If a player gets into too much physical contact, they may be given free throws which are worth one point each. The game typically lasts for four-quarters and the team with the most points at the end of the four-quarters win the game. If the score is tied at the end of the game, there will be additional play time, called overtime, to allow one team to win the match. The game is played between men's teams or between women's teams. Basketball has been played in the Summer Olympic Games since 1936. The shot clock rule started in 1954 for professional basketball. The first basketball game took place in 1892, where the court was half the size of what it is today. In 1891 the game was invented by James Naismith.", id:2},
{name: "volleyball",type:"sport",text:"Volleyball is a team sport. The teams are separated by a large net. It has six players on each side of the net. Each team is allowed twelve substitution players. The game starts when the captain from each team decides which side of the court they will play on, by the toss of a coin, which also determines who will serve (hit) the ball first. The point of the game is to keep the ball in the air. The ball can be played with any part of the body, with a maximum of three strokes a team. If at any point the ball hits the floor, the side that the ball landed on it is a point for the other team.History: <br>In 1895, William G. Morgan invented a new game called 'Mintonette'. However, when an observer named Alfred Halstead saw the game being played, he noticed the volleying action used to get the ball over the net, so he decided to change the name to 'volleyball'.Morgan wanted to create a skilled activity, which required more players, less space, and less exertion than basketball. The first net was a 'rope' and the fir",id:3}
])
function removeFromPress(news){
  console.log(news);
  console.log(press[0].id);
  press = press.filter(item => item.id != news.id);
  console.log(press);
}
export const usePress = () => {
  return {press: press,removeFromPress}
}
